"""
This type stub file was generated by pyright.
"""

import dataclasses

"""Some help text."""
@dataclasses.dataclass(order=True)
class Window:
    width: int
    height: int
    def area(self): # -> int:
        ...
    


def create_empty(): # -> Window:
    ...

