"""
This type stub file was generated by pyright.
"""

def tricky_function(): # -> int | None:
    ...

class TrickyClass:
    def __init__(self) -> None:
        ...
    
    def get_data(self): # -> int:
        ...
    


