import typing

class Window:
    width: int
    height: int
    def area(self: typing.Self) -> int: ...
    def __init__(self: typing.Self, width: int, height: int) -> None: ...
    def __lt__(self: typing.Self, other: typing.Any) -> bool: ...
    def __gt__(self: typing.Self, other: typing.Any) -> bool: ...
    def __le__(self: typing.Self, other: typing.Any) -> bool: ...
    def __ge__(self: typing.Self, other: typing.Any) -> bool: ...

def create_empty() -> Window: ...
